<?php
declare(strict_types=1);

/**
 * Request-side helpers: JSON body decoding and typed field extraction.
 *
 * The helpers coerce and bound every value they return. A route should never
 * hand a raw `$body['x']` to the database layer, even though the queries are
 * all prepared — bounding strings here is what keeps a 10 MB "notes" field
 * from reaching a VARCHAR(2000) column and failing at insert time.
 */

require_once __DIR__ . '/response.php';

/** Decoded JSON body, or an empty array when the body is empty. */
function request_body(): array
{
    static $body = null;
    if ($body !== null) {
        return $body;
    }

    $raw = file_get_contents('php://input');
    if ($raw === false || trim($raw) === '') {
        $body = [];
        return $body;
    }

    $decoded = json_decode($raw, true);
    if (!is_array($decoded)) {
        api_fail('invalid_json', 'Request body is not valid JSON.', 422);
    }

    $body = $decoded;
    return $body;
}

/** Required field: fails the request with 422 when absent or blank. */
function field_required(array $source, string $key): mixed
{
    $value = $source[$key] ?? null;
    if ($value === null || $value === '' || (is_array($value) && $value === [])) {
        api_fail('field_required', sprintf("Field '%s' is required.", $key), 422, ['field' => $key]);
    }
    return $value;
}

/** Trimmed, length-bounded string, or null. */
function field_string(array $source, string $key, int $maxLength = 255): ?string
{
    $value = $source[$key] ?? null;
    if (!is_string($value) && !is_numeric($value)) {
        return null;
    }
    $value = trim((string)$value);
    return $value === '' ? null : mb_substr($value, 0, $maxLength);
}

/** Integer, or null when absent or non-numeric. */
function field_int(array $source, string $key): ?int
{
    $value = $source[$key] ?? null;
    if ($value === null || $value === '' || !is_numeric($value)) {
        return null;
    }
    return (int)$value;
}

/** Float, or null. Accepts both `12.5` and `"12.5"`. */
function field_float(array $source, string $key): ?float
{
    $value = $source[$key] ?? null;
    if ($value === null || $value === '' || !is_numeric($value)) {
        return null;
    }
    return (float)$value;
}

/** Value constrained to a whitelist, or null when it is not in the list. */
function field_enum(array $source, string $key, array $allowed): ?string
{
    $value = field_string($source, $key, 40);
    return $value !== null && in_array($value, $allowed, true) ? $value : null;
}

/**
 * ISO 8601 timestamp from the client, converted to a UTC SQL datetime.
 *
 * Field devices are frequently offline for hours, so `performed_at` comes from
 * the handset clock and can be well in the past — that is expected and kept.
 * A timestamp in the *future* is not: it is clamped to now, so a handset with
 * a wrong clock cannot park a record beyond every future delta cursor.
 */
function field_timestamp(array $source, string $key, ?string $default = null): ?string
{
    $value = field_string($source, $key, 40);
    if ($value === null) {
        return $default;
    }
    $sql = iso_to_sql($value);
    if ($sql === null) {
        return $default;
    }
    $now = db_now();
    return $sql > $now ? $now : $sql;
}

/** A client_uuid as generated by the mobile app: a canonical UUID string. */
function field_client_uuid(array $source, string $key = 'client_uuid'): string
{
    $value = (string)field_required($source, $key);
    if (!preg_match('/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i', $value)) {
        api_fail('invalid_client_uuid', 'client_uuid must be a canonical UUID string.', 422, ['field' => $key]);
    }
    return strtolower($value);
}
